# Generated by Django 3.1.1 on 2020-09-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='fan',
            field=models.BooleanField(default=False),
        ),
    ]
